### ISSUE TITLE
Level_Design№2: Разработать прототип первого уровня с учетом доступных механик.

### ISSUE THREAD

**Issue by Kitsune424** [Kitsune424/COVEN_MovementFPS#21]
Необходимо прототипизровать первый уровень уже "сюжетной" части игры, в основу брать сценарий от writer, на уровне должна соблюдаться переменчивость напряжения за счет областей боя и областей платформинга, но и те и те области должны по максимуму использовать механики игры. Прототипы присылать на обсуждение в общий чат в телеграм, прототипизацию можно представлять в 3D блок схемах или в нарисованных схемах. У уровень должен быть изолированным (не подразумевать начало следующего уровня с точки конца прошлого). Финал работы сдать до  4.12.23, но все идеи и предложения нужно скидывать до этой даты.
(Время, выделенное на задачу от 30 минут до 2ч, в зависимости от исполнителя может быть разброс по времени)

**Comment by gachin05** [comment]
я считаю, что данный уровень должен пройти с меньшим количеством боевки. во время того, как пользователю будет рассказываться сюжет (в субтитрах), он будет находиться на некой военной зачищенной полуразрушенной базе террористов "Pandora". игроку будет доступно изучать локацию, использую игровые механики(бег по стенам, в виду разрушаемости базы; прыжки и приседания). в это время, игроку изредка будут попадаться враги
