### ISSUE TITLE
Level_Design№2.1: Придумать сценарий для первого уровня.

### ISSUE THREAD

**Issue by Kitsune424** [Kitsune424/COVEN_MovementFPS#22]
Нужно написать сценарий для первого уровня, должны быть распределены точки боя и точки платформинга, нужно определить настроение, внешний вид уровня и конечную цель (Убить кого-токонкретного, забрать объект, пройти за время, простой дойти до точки). Придумать интересные, но простореализуемые ситуации, которые могут возникнуть.
Сдать работу до 01.12.23, постоянно скидывать в issue правочные и прототипные варианты.

**Comment by gachin05** [comment]
[первый уровень.txt](https://github.com/Kitsune424/COVEN_MovementFPS/files/13504385/default.txt)

**Comment by gachin05** [comment]
[первый уровень.txt](https://github.com/Kitsune424/COVEN_MovementFPS/files/13537410/default.txt)
