### ISSUE TITLE
[DESIGN] иконки

### ISSUE THREAD

**Issue by Kitsune424** [Kitsune424/COVEN_MovementFPS#26]
Для игры необходимо сделать иконки для оружия. Иконки должны быть в формате .PNG без фона, белые однотонные, не меньше разрешения 800x400px (максимальное 1000x700px) DPI 100.  Свободного пространства должно быть минимум. Для разработки этих самых иконок используйте скриншоты самих моделей. Работу можно выполнять в Photoshop, adobe illustrator и т.д, главное чтобы соблюдались условия по разрешению и формату.
На задачу выделено 1-2ч времени, сдать работу до 15.12.23.

AR 181
![image](https://github.com/Kitsune424/COVEN_MovementFPS/assets/60034144/0d967296-f48d-48d3-902d-a132ef47ce7d)

SMG
![image](https://github.com/Kitsune424/COVEN_MovementFPS/assets/60034144/465e2c12-4329-481a-88df-8a8d5c5b5fe5)

SR 2
![image](https://github.com/Kitsune424/COVEN_MovementFPS/assets/60034144/0594eea5-f399-47a6-9745-baae5f28b89e)

Re 17
![image](https://github.com/Kitsune424/COVEN_MovementFPS/assets/60034144/7ca71770-df0d-46c0-a79e-e9d7284049ce)

**Comment by Rina044** [comment]
![иконка 1](https://github.com/Kitsune424/COVEN_MovementFPS/assets/147870458/71a27e4f-e631-4b1f-86a0-54fef8794ed8)
![иконка 2](https://github.com/Kitsune424/COVEN_MovementFPS/assets/147870458/8800d155-3f73-4b2e-ae55-ea9150158098)
![иконка 3](https://github.com/Kitsune424/COVEN_MovementFPS/assets/147870458/5f92a447-4b09-49cd-8cac-04c693456391)
![иконка 4](https://github.com/Kitsune424/COVEN_MovementFPS/assets/147870458/f49926ff-a587-4fb3-bb58-9468678d9dc5)

**Comment by Rina044** [comment]
![иконка1](https://github.com/Kitsune424/COVEN_MovementFPS/assets/147870458/f579bcd4-39bf-49d8-8615-335560d20395)
![иконка2](https://github.com/Kitsune424/COVEN_MovementFPS/assets/147870458/e5fcce8e-5946-458c-87dd-61afa3b3157d)
![иконка3](https://github.com/Kitsune424/COVEN_MovementFPS/assets/147870458/7ecfefe3-7735-423b-950d-55807452cecc)
![иконка4](https://github.com/Kitsune424/COVEN_MovementFPS/assets/147870458/d45877ea-3a01-4aae-a0cb-ca398749c9fb)
