### ISSUE TITLE
[DESIGN] Разработать дизайн интерфейса для игрока

### ISSUE THREAD

**Issue by Kitsune424** [Kitsune424/COVEN_MovementFPS#27]
Для игры необходимо разработать UI внутри игры, который будет отображать информацию об нынешнем типе оружии, количестве патрон в  данный момент  (кол-во патрон в магазине / кол-во патрон осталось всего), информация о кол-ве гранат.
Интерфейс должен быть исполнен в монотонном белом цвете, предоставляться ввиде ссылки на FIGMA проект прикрепленной в комментарии issue. Работу сдать 15.12.23, на задачу отведено 1-2ч работы (вариация в зависимости от кол-ва правок)

**Comment by NiKiToSchika** [comment]
https://www.figma.com/file/6e2OpM1imzg9NMSHCCqESi/Untitled?type=design&node-id=0%3A1&mode=design&t=ygvMhl6lBmC9zjkN-1
