### ISSUE TITLE
[DESIGN] иконка игры

### ISSUE THREAD

**Issue by Kitsune424** [Kitsune424/COVEN_MovementFPS#28]
Для исполняемого файла игры необходимо разработать иконку ярлыка. Делать можно в чем угодно, главная задача:
основной цвет - черный, размер иконки 256х256 пикселей, формат изображения .ico и .bmp (2 файла). Дизайн должен содержать простое однородное изображение, которое было бы читаемо на расстоянии и при малых размерах. Время выполнения задачи - 1ч, срок сдачи 20.10.23.

**Comment by Rina044** [comment]
![ярлык](https://github.com/Kitsune424/COVEN_MovementFPS/assets/147870458/01726283-1aa5-4c79-8f83-7788ddca59db)
