### ISSUE TITLE
[Writer] Описание противников

### ISSUE THREAD

**Issue by Kitsune424** [Kitsune424/COVEN_MovementFPS#29]
Придумать описательный образ противника (болванчика) которые будут в игре. Необходимо придумать внешность противника или их вариации (классы), которые будут раскиданы по уровню. Описание внешности должно учитывать уже имеющуюся стилистику игры и быть подробным, чтобы данное описание дальше пошло на проивзодство дизайнерам и программисту.
Описание размеров, формы, оружия, особенностей, частота стрельбы, меткость, количество здоровья, урон и т.д.
Время на задачу 3ч (будет много работы над продумыванием особенностей). Срок сдачи 22.12.23.

**Comment by gachin05** [comment]
[противники.txt](https://github.com/Kitsune424/COVEN_MovementFPS/files/13752118/default.txt)
описание противников
