### ISSUE TITLE
[Writer] придумать текст презентации проекта

### ISSUE THREAD

**Issue by Kitsune424** [Kitsune424/COVEN_MovementFPS#30]
23.12.23  будет презентация проекта, необходимо придумать текст быстро и подробно описывающий игру и процесс разработки.
Время выступления 3 минуты. Время на задачу 1ч, срок сдачи 22.12.23.

**Comment by gachin05** [comment]
[текст для презентации.txt](https://github.com/Kitsune424/COVEN_MovementFPS/files/13752559/default.txt)
текст перзентации
