### ISSUE TITLE
[Designer] сделать визуальную презентацию в PowerPoint

### ISSUE THREAD

**Issue by Kitsune424** [Kitsune424/COVEN_MovementFPS#31]
Смотри Issue https://github.com/Kitsune424/COVEN_MovementFPS/issues/30.
Нужно на основе текста подготовить презентацию по игре. Все медиа материалы спрашивайте у меня.
Презентация должна быть выполнена в Powerpoint  минимум текста, много визуала, можно не использовать анимации.
Время на выполнение задачи 1ч. Срок сдачи 22.12.23.

**Comment by NiKiToSchika** [comment]
[Презентация123.pptx](https://github.com/Kitsune424/COVEN_MovementFPS/files/13752968/123.pptx)
