### ISSUE TITLE
ЛОР_№1: Написание лора игры

### ISSUE THREAD

**Issue by Kitsune424** [Kitsune424/COVEN_MovementFPS#8]
Определение основных элементов лора.

- Определить основную историческую эпоху или фантастический мир, в котором разворачивается игра (время и место, например 2083 год, система колонизированных солнечных систем "ФРОНИТР").

- Обосновать механики игры:
наш герой (игрок) является солдатом экспериментального подразделения C.O.V.E.N. Группировка была создана для решения только самых сложных и особых задач, которые требуют мгновенных и точных решений. се солдаты C.O.V.E.N. имеют уникальные навыки и способности, что позволяет им выполнять задачи, на которые обычные военные подразделения не способны. Среди обычных подразделений солдаты C.O.V.E.N получили прозвища "Revenant'ы" (призраки), т.к их способности передвижения превышают человеческие, на поле боя за ними очень сложно уследить. "Наш отряд был уничтожен будто призраками, я  лишь увидел нечеткие силуэты, прежде чем остался один" сказал на допросе один из солдат террористической группировки  "Pandora".
(персонаж игрока оснащен реактивным ранцем, который позволяет высоко прыгать и бегать по стенам)

- Определить основной конфликт или задачу, которую игрок будет решать во время игры.
Основной противник - террористическая группировка "Pandora". Нужно придумать общую концепцию что и почему происходит (противник, его цель, конфликт, задача игрока)

Можно адаптировать или заимствовать некоторые элементы с других проектов. Дата сдачи: 19.11.2023

**Comment by gachin05** [comment]
[лор C.O.V.E.N..txt](https://github.com/Kitsune424/COVEN_MovementFPS/files/13404397/C.O.V.E.N.txt)

**Comment by gachin05** [comment]
[лор C.O.V.E.N..txt](https://github.com/Kitsune424/COVEN_MovementFPS/files/13404401/C.O.V.E.N.txt)

**Comment by gachin05** [comment]
[лор C.O.V.E.N..txt](https://github.com/Kitsune424/COVEN_MovementFPS/files/13404433/C.O.V.E.N.txt)
