### ISSUE TITLE
ЛОР_№2: Придумать описание игры.

### ISSUE THREAD

**Issue by Kitsune424** [Kitsune424/COVEN_MovementFPS#9]
Описание должно быть четкое и конкретное, содержать информацию о ее жанре, геймплее, целях. (FPS, movement shooter, исходя из лора)
 Описание должно состоять из не менее чем 200 слов и содержать все необходимые детали, чтобы игроки могли понять суть игры и принять решение о ее игре.
 Описание игры должно быть соответствующим требованиям и предпочтениям целевой аудитории. Необходимо учитывать интересы и предпочтения потенциальных игроков, чтобы привлечь их внимание и заинтересовать.
 Описание игры должно быть завершено в течение 1 недели. Этот срок должен быть достаточным, чтобы провести исследование, разработать концепцию игры и сформулировать ее описание.
 
 Пример:
 "C.O.V.E.N Revenant" - это интенсивный шутер от первого лица, где игрок берет на себя роль солдата экспериментального подразделения C.O.V.E.N. Отряд был создан для решения самых сложных и особых задач, требующих мгновенных и точных решений. "C.O.V.E.N Revenant" предлагает захватывающий геймплей с быстрыми перестрелками, динамичными схватками и захватывающими миссиями. Вам предстоит сражаться с разнообразными врагами, использовать свой реактивный ранец для тактических преимуществ и применять разнообразное оружие, чтобы оставить за собой лишь неясные силуэты и победить врагов.
Присоединитесь к отряду C.O.V.E.N и станьте настоящим "Revenant'ом", чтобы справиться с самыми сложными и опасными задачами, которые требуют невероятной скорости и мастерства в передвижении. Войдите в мир "C.O.V.E.N Revenant" и станьте непобедимым призраком на поле боя."

**Comment by gachin05** [comment]
[лор C.O.V.E.N..txt](https://github.com/Kitsune424/COVEN_MovementFPS/files/13404385/C.O.V.E.N.txt)

**Comment by gachin05** [comment]
извини, перепутал вкладку
сюда переотправлю описание

**Comment by gachin05** [comment]
[описание C.O.V.E.N..txt](https://github.com/Kitsune424/COVEN_MovementFPS/files/13404436/C.O.V.E.N.txt)
